SET ECHO OFF
SET TERM OFF
SET FEEDBACK OFF
SET LINES 200
SET TRIMSPO ON
SET DEFINE ON
SET VERIFY OFF
SET HEAD OFF
SET PAGES 0
SET TIME OFF
SET TIMING OFF


ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';
SET TERM ON
