SET TERM OFF
SET DEFINE ON
SET ECHO OFF
SET FEEDBACK OFF
SET HEAD OFF
SET LINES 200 
SET PAGES 0
SET TIME   OFF
SET TIMING OFF
SET TRIMSPO ON 
SET VERIFY OFF

-- columns
COL NAME  FORMAT A30
COL VALUE FORMAT A30

-- date output format
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD HH24:MI:SS';

-- END
SET TERM ON 
